from tkinter import *
from tkinter import ttk
root = Tk()
root.title("Registration Form")
root.geometry("400x400")
frame = ttk.Frame(root, padding="3 3 12 12")
frame.grid(column=0, row=0, sticky=(N, W, E, S))
regNoLabel = ttk.Label(frame, text="Registration Number")
regNoLabel.grid(column=0, row=0, sticky=W)
regNo = ttk.Entry(frame)
regNo.grid(column=1, row=0, sticky=(W, E))
nameLabel = ttk.Label(frame, text="Name")
nameLabel.grid(column=0, row=1, sticky=W)
name = ttk.Entry(frame)
name.grid(column=1, row=1, sticky=(W, E))
deptLabel = ttk.Label(frame, text="Department")
deptLabel.grid(column=0, row=2, sticky=W)
dept = ttk.Entry(frame)
dept.grid(column=1, row=2, sticky=(W, E))
dept.insert(0, "CSE")
genderLabel = ttk.Label(frame, text="Gender")
genderLabel.grid(column = 0,row = 3, sticky=W)
maleRadioButton = ttk.Radiobutton(frame,text = "Male",value=0)
maleRadioButton.grid(column=1, row=3, sticky=(W, E))
femaleRadioButton = ttk.Radiobutton(frame,text = "Female",value=1)
femaleRadioButton.grid(column=2, row=3, sticky=(W, E))
ageLabel = ttk.Label(frame,text = "Age")
ageLabel.grid(column = 0, row = 4, sticky = W)
ageSpinbox = ttk.Spinbox(frame,from_=0,to=200)
ageSpinbox.grid(column=1, row=4, sticky=(W, E))
ageSpinbox.insert(0, "18")
insertButton = ttk.Button(frame, text="Insert")
insertButton.grid(column=0, row=5, sticky=(W, E))
updateButton = ttk.Button(frame, text="Update")
updateButton.grid(column=1, row=5, sticky=(W, E))
deleteButton = ttk.Button(frame, text="Delete")
deleteButton.grid(column=0, row=6, sticky=(W, E))
selectButton = ttk.Button(frame, text="Select")
selectButton.grid(column=1, row=6, sticky=(W, E))
root.mainloop()